# Generated by Django 4.2.7 on 2023-12-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(related_name='Products', to='main_page.product'),
        ),
    ]
