# Generated by Django 4.2.7 on 2023-12-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_alter_subcategories_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='ProductReviews'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, related_name='Seller', to='main_page.productreviews'),
        ),
    ]
